data = [
    {'name': 'Instagram', 'follower_count': 686, 'description': 'Piattaforma di social media', 'country': 'Stati Uniti'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 651, 'description': 'Calciatore', 'country': 'Portogallo'},
    {'name': 'Lionel Messi', 'follower_count': 505, 'description': 'Calciatore', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 421, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Dwayne Johnson', 'follower_count': 394, 'description': 'Attore e ex wrestler', 'country': 'Stati Uniti'},
    {'name': 'Kylie Jenner', 'follower_count': 394, 'description': 'Personaggio televisivo e imprenditrice', 'country': 'Stati Uniti'},
    {'name': 'Ariana Grande', 'follower_count': 376, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Kim Kardashian', 'follower_count': 357, 'description': 'Personaggio televisivo e imprenditrice', 'country': 'Stati Uniti'},
    {'name': 'Beyoncé', 'follower_count': 312, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Khloé Kardashian', 'follower_count': 303, 'description': 'Personaggio televisivo e imprenditrice', 'country': 'Stati Uniti'},
    {'name': 'Nike', 'follower_count': 301, 'description': 'Azienda di abbigliamento sportivo', 'country': 'Stati Uniti'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Cantante', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 288, 'description': 'Modella e personaggio televisivo', 'country': 'Stati Uniti'},
    {'name': 'Taylor Swift', 'follower_count': 282, 'description': 'Cantante e cantautrice', 'country': 'Stati Uniti'},
    {'name': 'National Geographic', 'follower_count': 279, 'description': 'Rivista e organizzazione scientifica', 'country': 'Stati Uniti'},
    {'name': 'Virat Kohli', 'follower_count': 270, 'description': 'Crickettista', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 249, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Neymar', 'follower_count': 229, 'description': 'Calciatore', 'country': 'Brasile'},
    {'name': 'Nicki Minaj', 'follower_count': 226, 'description': 'Rapper e cantautrice', 'country': 'Trinidad e Tobago'},
    {'name': 'Kourtney Kardashian', 'follower_count': 219, 'description': 'Personaggio televisivo e imprenditrice', 'country': 'Stati Uniti'},
    {'name': 'Miley Cyrus', 'follower_count': 213, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Katy Perry', 'follower_count': 204, 'description': 'Cantante', 'country': 'Stati Uniti'},
    {'name': 'Zendaya', 'follower_count': 179, 'description': 'Attrice e cantante', 'country': 'Stati Uniti'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comico e attore', 'country': 'Stati Uniti'},
    {'name': 'Real Madrid CF', 'follower_count': 173, 'description': 'Club di calcio', 'country': 'Spagna'},
    {'name': 'Cardi B', 'follower_count': 164, 'description': 'Rapper e attrice', 'country': 'Stati Uniti'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'Demi Lovato', 'follower_count': 153, 'description': 'Cantante e attrice', 'country': 'Stati Uniti'},
    {'name': 'Rihanna', 'follower_count': 149, 'description': 'Cantante e imprenditrice', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Cantante e ballerino', 'country': 'Stati Uniti'},
    {'name': 'Drake', 'follower_count': 143, 'description': 'Rapper e cantautore', 'country': 'Canada'},
    {'name': 'Ellen DeGeneres', 'follower_count': 136, 'description': 'Comica e conduttrice televisiva', 'country': 'Stati Uniti'},
    {'name': 'FC Barcelona', 'follower_count': 136, 'description': 'Club di calcio', 'country': 'Spagna'},
    {'name': 'Kylian Mbappé', 'follower_count': 123, 'description': 'Calciatore', 'country': 'Francia'},
    {'name': 'Billie Eilish', 'follower_count': 123, 'description': 'Cantante', 'country': 'Stati Uniti'},
    {'name': 'UEFA Champions League', 'follower_count': 119, 'description': 'Competizione calcistica per club', 'country': 'Europa'},
    {'name': 'Gal Gadot', 'follower_count': 108, 'description': 'Attrice', 'country': 'Israele'},
    {'name': 'Lisa', 'follower_count': 105, 'description': 'Cantante e ballerina', 'country': 'Thailandia'},
    {'name': 'Vin Diesel', 'follower_count': 103, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'NASA', 'follower_count': 96.8, 'description': 'Agenzia spaziale', 'country': 'Stati Uniti'},
    {'name': 'Shraddha Kapoor', 'follower_count': 94.2, 'description': 'Attrice', 'country': 'India'},
    {'name': 'Narendra Modi', 'follower_count': 92.5, 'description': 'Primo Ministro dell\'India', 'country': 'India'},
    {'name': 'Priyanka Chopra', 'follower_count': 92.5, 'description': 'Attrice', 'country': 'India'},
    {'name': 'Snoop Dogg', 'follower_count': 91.3, 'description': 'Rapper', 'country': 'Stati Uniti'},
    {'name': 'Blackpink', 'follower_count': 90.6, 'description': 'Girl group musicale', 'country': 'Corea del Sud'},
    {'name': 'Shakira', 'follower_count': 90.2, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'Gigi Hadid', 'follower_count': 89.7, 'description': 'Modella', 'country': 'Stati Uniti'},
    {'name': 'Alia Bhatt', 'follower_count': 89.2, 'description': 'Attrice', 'country': 'India'},
    {'name': 'Karim Benzema', 'follower_count': 88.9, 'description': 'Calciatore', 'country': 'Francia'},
    {'name': 'Shawn Mendes', 'follower_count': 88.4, 'description': 'Cantante', 'country': 'Canada'},
    {'name': 'Emma Watson', 'follower_count': 88.1, 'description': 'Attrice', 'country': 'Regno Unito'},
    {'name': 'David Beckham', 'follower_count': 87.6, 'description': 'Ex calciatore', 'country': 'Regno Unito'},
    {'name': 'Zlatan Ibrahimović', 'follower_count': 86.8, 'description': 'Calciatore', 'country': 'Svezia'},
    {'name': 'The Rock', 'follower_count': 85.3, 'description': 'Attore e ex wrestler', 'country': 'Stati Uniti'},
    {'name': 'Bruno Mars', 'follower_count': 84.7, 'description': 'Cantante', 'country': 'Stati Uniti'},
    {'name': 'Dua Lipa', 'follower_count': 83.4, 'description': 'Cantante', 'country': 'Regno Unito'},
    {'name': 'Luis Suárez', 'follower_count': 82.9, 'description': 'Calciatore', 'country': 'Uruguay'},
    {'name': 'Robert Downey Jr.', 'follower_count': 82.5, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Will Smith', 'follower_count': 81.9, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Chris Hemsworth', 'follower_count': 80.5, 'description': 'Attore', 'country': 'Australia'},
    {'name': 'Camila Cabello', 'follower_count': 79.8, 'description': 'Cantante', 'country': 'Stati Uniti'},
    {'name': 'Justin Timberlake', 'follower_count': 79.4, 'description': 'Cantante e attore', 'country': 'Stati Uniti'},
    {'name': 'Conor McGregor', 'follower_count': 78.9, 'description': 'Lottatore di MMA', 'country': 'Irlanda'},
    {'name': 'Ed Sheeran', 'follower_count': 78.2, 'description': 'Cantante', 'country': 'Regno Unito'},
    {'name': 'Anitta', 'follower_count': 77.5, 'description': 'Cantante', 'country': 'Brasile'},
    {'name': 'Tom Holland', 'follower_count': 76.9, 'description': 'Attore', 'country': 'Regno Unito'},
    {'name': 'Maluma', 'follower_count': 76.3, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'Mohamed Salah', 'follower_count': 75.8, 'description': 'Calciatore', 'country': 'Egitto'},
    {'name': 'Sebastián Yatra', 'follower_count': 75.1, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'Shay Mitchell', 'follower_count': 74.4, 'description': 'Attrice e modella', 'country': 'Canada'},
    {'name': 'James Rodríguez', 'follower_count': 73.9, 'description': 'Calciatore', 'country': 'Colombia'},
    {'name': 'Karol G', 'follower_count': 73.5, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'C. Tangana', 'follower_count': 72.8, 'description': 'Cantante', 'country': 'Spagna'},
    {'name': 'Paulo Dybala', 'follower_count': 72.3, 'description': 'Calciatore', 'country': 'Argentina'},
    {'name': 'Marcelo Vieira', 'follower_count': 71.8, 'description': 'Calciatore', 'country': 'Brasile'},
    {'name': 'Megan Fox', 'follower_count': 71.2, 'description': 'Attrice', 'country': 'Stati Uniti'},
    {'name': 'Eva Longoria', 'follower_count': 70.9, 'description': 'Attrice', 'country': 'Stati Uniti'},
    {'name': 'Bad Bunny', 'follower_count': 70.3, 'description': 'Cantante', 'country': 'Porto Rico'},
    {'name': 'James Harden', 'follower_count': 69.8, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'Russell Westbrook', 'follower_count': 69.2, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'Lil Wayne', 'follower_count': 68.7, 'description': 'Rapper', 'country': 'Stati Uniti'},
    {'name': 'Luka Modrić', 'follower_count': 68.1, 'description': 'Calciatore', 'country': 'Croazia'},
    {'name': 'Gareth Bale', 'follower_count': 67.6, 'description': 'Calciatore', 'country': 'Galles'},
    {'name': 'Karim Benzema', 'follower_count': 67.1, 'description': 'Calciatore', 'country': 'Francia'},
    {'name': 'Manny Pacquiao', 'follower_count': 66.7, 'description': 'Pugile e politico', 'country': 'Filippine'},
    {'name': 'J Balvin', 'follower_count': 66.2, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'Carlos Vives', 'follower_count': 65.8, 'description': 'Cantante', 'country': 'Colombia'},
    {'name': 'Zinedine Zidane', 'follower_count': 65.3, 'description': 'Allenatore ed ex calciatore', 'country': 'Francia'},
    {'name': 'Antonio Brown', 'follower_count': 64.9, 'description': 'Giocatore di football americano', 'country': 'Stati Uniti'},
    {'name': 'Jayson Tatum', 'follower_count': 64.5, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'Harry Styles', 'follower_count': 64.2, 'description': 'Cantante e attore', 'country': 'Regno Unito'},
    {'name': 'Travis Scott', 'follower_count': 63.8, 'description': 'Rapper e produttore', 'country': 'Stati Uniti'},
    {'name': 'Post Malone', 'follower_count': 63.5, 'description': 'Cantante e rapper', 'country': 'Stati Uniti'},
    {'name': 'The Weeknd', 'follower_count': 63.1, 'description': 'Cantante', 'country': 'Canada'},
    {'name': 'Zayn Malik', 'follower_count': 62.7, 'description': 'Cantante', 'country': 'Regno Unito'},
    {'name': 'Gordon Ramsay', 'follower_count': 62.3, 'description': 'Chef e personaggio TV', 'country': 'Regno Unito'},
    {'name': 'Samuel L. Jackson', 'follower_count': 61.9, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Tyler, The Creator', 'follower_count': 61.5, 'description': 'Rapper e produttore', 'country': 'Stati Uniti'},
    {'name': 'Eminem', 'follower_count': 61.1, 'description': 'Rapper', 'country': 'Stati Uniti'},
    {'name': 'James Franco', 'follower_count': 60.8, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Andrés Iniesta', 'follower_count': 60.4, 'description': 'Calciatore', 'country': 'Spagna'},
    {'name': 'Jared Leto', 'follower_count': 60.1, 'description': 'Attore e cantante', 'country': 'Stati Uniti'},
    {'name': 'Usain Bolt', 'follower_count': 59.7, 'description': 'Velocista', 'country': 'Giamaica'},
    {'name': 'Paul Pogba', 'follower_count': 59.3, 'description': 'Calciatore', 'country': 'Francia'},
    {'name': 'Sergio Ramos', 'follower_count': 58.9, 'description': 'Calciatore', 'country': 'Spagna'},
    {'name': 'David Guetta', 'follower_count': 58.5, 'description': 'DJ e produttore', 'country': 'Francia'},
    {'name': 'Marshmello', 'follower_count': 58.2, 'description': 'DJ e produttore', 'country': 'Stati Uniti'},
    {'name': 'Hugh Jackman', 'follower_count': 57.8, 'description': 'Attore', 'country': 'Australia'},
    {'name': 'Rafael Nadal', 'follower_count': 57.4, 'description': 'Tennista', 'country': 'Spagna'},
    {'name': 'Stephen Curry', 'follower_count': 57.1, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'J Cole', 'follower_count': 56.7, 'description': 'Rapper e produttore', 'country': 'Stati Uniti'},
    {'name': 'Lana Del Rey', 'follower_count': 56.3, 'description': 'Cantante', 'country': 'Stati Uniti'},
    {'name': 'Shane Dawson', 'follower_count': 56.0, 'description': 'YouTuber e autore', 'country': 'Stati Uniti'},
    {'name': 'PewDiePie', 'follower_count': 55.6, 'description': 'YouTuber e creatore di contenuti', 'country': 'Svezia'},
    {'name': 'Diddy', 'follower_count': 55.2, 'description': 'Rapper e imprenditore', 'country': 'Stati Uniti'},
    {'name': 'Fernando Alonso', 'follower_count': 54.9, 'description': 'Pilota di Formula 1', 'country': 'Spagna'},
    {'name': 'Tom Brady', 'follower_count': 54.5, 'description': 'Ex giocatore di football americano', 'country': 'Stati Uniti'},
    {'name': 'Ricky Martin', 'follower_count': 54.1, 'description': 'Cantante', 'country': 'Porto Rico'},
    {'name': 'Simone Biles', 'follower_count': 53.7, 'description': 'Ginnasta', 'country': 'Stati Uniti'},
    {'name': 'Tony Hawk', 'follower_count': 53.3, 'description': 'Skater professionista', 'country': 'Stati Uniti'},
    {'name': 'Damian Lillard', 'follower_count': 52.9, 'description': 'Giocatore di basket', 'country': 'Stati Uniti'},
    {'name': 'Lorde', 'follower_count': 52.6, 'description': 'Cantante', 'country': 'Nuova Zelanda'},
    {'name': 'Ricardo Kaká', 'follower_count': 52.2, 'description': 'Ex calciatore', 'country': 'Brasile'},
    {'name': 'Daniel Ricciardo', 'follower_count': 51.8, 'description': 'Pilota di Formula 1', 'country': 'Australia'},
    {'name': 'Jamie Foxx', 'follower_count': 51.4, 'description': 'Attore e cantante', 'country': 'Stati Uniti'},
    {'name': 'Channing Tatum', 'follower_count': 51.1, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Machine Gun Kelly', 'follower_count': 50.7, 'description': 'Cantante e rapper', 'country': 'Stati Uniti'},
    {'name': 'Bad Bunny Official', 'follower_count': 50.3, 'description': 'Cantante', 'country': 'Porto Rico'},
    {'name': 'Lewis Hamilton', 'follower_count': 50.0, 'description': 'Pilota di Formula 1', 'country': 'Regno Unito'},
    {'name': 'Sadio Mané', 'follower_count': 49.7, 'description': 'Calciatore', 'country': 'Senegal'},
    {'name': 'Javier Hernández (Chicharito)', 'follower_count': 49.3, 'description': 'Calciatore', 'country': 'Messico'},
    {'name': 'Ronda Rousey', 'follower_count': 48.9, 'description': 'Lottatrice di MMA e wrestler', 'country': 'Stati Uniti'},
    {'name': 'Chris Pratt', 'follower_count': 48.6, 'description': 'Attore', 'country': 'Stati Uniti'},
    {'name': 'Canelo Álvarez', 'follower_count': 48.2, 'description': 'Pugile', 'country': 'Messico'},
    {'name': 'Anderson Silva', 'follower_count': 47.9, 'description': 'Lottatore di MMA', 'country': 'Brasile'},
    {'name': 'Blake Lively', 'follower_count': 47.5, 'description': 'Attrice', 'country': 'Stati Uniti'}
]